#- name: Cleanup existing VPN installation
#  command: "{{ vpn_corp }}-vpnc uninstall -dd {{ vpn_dir }} -f"
#  when: clean_up|bool

- name: Install VPN client
  command: "{{ vpn_corp }}-vpnc install --dnsmasq -dd {{ vpn_dir }} -ds {{ service_dir }} -vv"
  register: vpn_install
