---
- name: Transfer client certificate
  copy:
    src: "credentials/{{ vpn_cert }}"
    dest: "{{ app_dir }}/"
    owner: root
    group: root
    mode: 0600

- name: Transfer client private key
  copy:
    src: "credentials/{{ vpn_prv_key }}"
    dest: "{{ app_dir }}/"
    owner: root
    group: root
    mode: 0600

- name: Configure VPN client with client certificate authentication
  command: |
    "{{ vpn_corp }}-vpnc add -sh {{ vpn_server }} -sp {{ vpn_port }} -su {{ vpn_hub }} -ca {{ vpn_account }} -ct cert \
        -cu {{ vpn_user }} -cpk {{ app_dir }}/{{ vpn_prv_key }} -cck {{ app_dir }}/{{ vpn_cert }} -v"
  register: vpn_configure
  ignore_errors: True
  when: vpn_install.rc == 0
