- name: Extend VPNC subscription
  hosts: all
  vars_files:
    - vars/global_vars.yml

  tasks:
    - name: Populate remote machine
      when: args_skip_populate is not defined or not args_skip_populate
      include_tasks: tasks/min_facts.yml

    - name: Prepare credential
      include_role:
        name: prepare-credential
      vars:
        runtime_cert_lookup_key: "{{ inventory_hostname }}"

    - name: Check VPNC state
      when: args_skip_populate is not defined or not args_skip_populate
      include_role:
        name: vpnc-state
      vars:
        args_vpn_state_assert_install: True

    - name: Add VPN account
      include_role:
        name: vpnc-extend
      vars:
        runtime_vpn_conn: "{{ resp_prepare_credential }}"

    - name: Fix Connman DHClient if needed
      include_role:
        name: connman-dhclient

    - name: Validate VPNC state
      include_role:
        name: vpnc-state
      vars:
        args_vpn_state_show: True
        args_vpn_state_assert_work: True
