---
- name: Uninstall VPN client
  command: "{{ vpnc_cli }} uninstall {{ '-f' if arg_vpn_uninstall_force else '' }} {{ '--keep-dnsmasq' if arg_vpn_keep_dnsmasq else '--no-keep-dnsmasq' }}"
  register: vpnc_uninstall

- name: Debug VPNC uninstall output
  when: debug is defined
  ansible.builtin.debug:
    msg: "{{ vpnc_uninstall }}"

- name: Check whether VPNC CLI is installed in system path
  when: ansible_facts['os_family'] != 'Windows'
  command: "which {{ vpnc_cli }}"
  register: is_exec
  ignore_errors: yes

- name: Remove VPNC CLI
  when: arg_vpn_remove_cli and is_exec.rc == 0
  ansible.builtin.file:
    path: "{{ is_exec.stdout }}"
    state: absent
