- name: Check whether VPNC CLI is installed in system path
  when: ansible_facts['os_family'] != 'Windows'
  command: "which {{ vpnc_cli }}"
  register: runtime_is_exec
  ignore_errors: yes

- name: Evaluate VPNC installed
  when: not ansible_check_mode
  ansible.builtin.set_fact:
    resp_vpnc_state: |
      {{ resp_vpnc_state | combine({  'is_exec': runtime_is_exec.rc == 0,
                                      'error': None if runtime_is_exec.rc == 0 else runtime_is_exec.msg }) }}

- name: Check VPNC CLI version
  when: not ansible_check_mode and runtime_is_exec.rc == 0
  command: "{{ vpnc_cli }} version --json"
  register: runtime_is_ver
  ignore_errors: yes

- name: Evaluate VPNC version
  when: not ansible_check_mode and runtime_is_exec.rc == 0
  ansible.builtin.set_fact:
    resp_vpnc_state: |
      {{ resp_vpnc_state | combine({  'is_broken': runtime_is_ver.rc != 0,
                                      'version': (runtime_is_ver.stdout | from_json) if runtime_is_ver.rc == 0 else None,
                                      'error': None if runtime_is_ver.rc == 0 else runtime_is_ver.msg }) }}
