- name: Check VPNC service status
  when: vpnc_installed.rc == 0
  command: "{{ vpn_corp }}-vpnc status --json"
  register: vpnc_status
  ignore_errors: yes

- name: Debug VPNC service status
  when: vpnc_installed.rc == 0 and debug is defined
  ansible.builtin.debug:
    msg: "{{ vpnc_status | ternary(vpnc_status.stdout | from_json, vpnc_status) }}"
