- name: Check VPNC service status
  when: not ansible_check_mode and is_exec.rc == 0 and is_ver.rc == 0
  command: "{{ vpnc_cli }} status {{ arg_vpn_test_domains | map('regex_replace', '^(.*)$', '--domain \\1') | join(' ') }} --json"
  register: is_status
  ignore_errors: yes

- name: Evaluate VPNC service status
  when: not ansible_check_mode and is_exec.rc == 0 and is_ver.rc == 0
  ansible.builtin.set_fact:
    vpnc_state: "{{ vpnc_state | combine({  'status': (is_status.stdout | from_json) if is_status.stdout else None,
                                            'status_rc': is_status.rc, \
                                            'error': is_status.stderr if (is_status.stderr | default('')) else (is_status.msg | default('')) }) }}"
