- name: Upgrade VPNC version
  command: "{{ vpnc_cli }} upgrade"
  register: vpnc_upgrade

- name: Debug VPNC upgrade output
  when: debug is defined
  ansible.builtin.debug:
    msg: "{{ vpnc_upgrade }}"
