/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.zero88.qwe.vpn.java-application-conventions")
}

dependencies {
    implementation(project(":spi"))
}

application {
    // Define the main class for the application.
    mainClass.set("io.zero88.qwe.vpn.app.App")
}
