---
- name: Transfer binary
  copy:
    src: binary/qweio-vpnc-amd64
    dest: "{{ vpn_dir }}/"
    owner: root
    group: root
    mode: u+x,g+x
  when: ansible_architecture == "x86_64"

- name: Create symlink
  file:
    src: "{{ vpn_dir }}/qweio-vpnc-amd64"
    dest: "{{ bin_path }}/qweio-vpnc"
    owner: root
    group: root
    state: link

- name: Cleanup existing VPN installation
  command: qweio-vpnc uninstall -dd {{ vpn_dir }}/vpnclient -f
  when: clean_up|bool

- name: Install VPN client
  command: qweio-vpnc install --auto-startup --dnsmasq -dd {{ vpn_dir }}/vpnclient -dn {{ vpn_service }} -ds {{ service_dir }} -vv
  register: vpn_install
  ignore_errors: True

- include: vpn_cert.yml
  when: vpn_cert is defined

- include: vpn_password.yml
  when: vpn_password is defined