---
- name: Transfer VPNC CLI binary by arch
  copy:
    src: "qweio-vpnc-{{ arch_mapping[ansible_architecture] }}"
    dest: "{{ arg_app_dir }}/{{ vpnc_cli }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Create executable symlink for VPNC CLI
  file:
    src: "{{ arg_app_dir }}/{{ vpnc_cli }}"
    dest: "{{ unix_bin_dir }}/{{ vpnc_cli }}"
    owner: root
    group: root
    state: link
    force: true
