---
- name: Configure VPN client with password authentication
  command: |
    {{ vpnc_cli }} add -sh {{ runtime_vpn_conn.vpn_server }} -sp {{ runtime_vpn_conn.vpn_port }}
    -su {{ runtime_vpn_conn.vpn_hub }} -ca {{ runtime_vpn_conn.vpn_account }} -ct password -cd
    -cu {{ runtime_vpn_conn.vpn_user }} -cp {{ runtime_vpn_conn.vpn_password }} -v
  register: resp_vpnc_configure
