arch_mapping:
  armv7l: armv7
  x86_64: amd64

vpn_corp: qweio
vpnc_cli: "{{ vpn_corp }}-vpnc"
vpnc_artifact: qweio-vpnc
arg_app_dir: /app
arg_vpn_dir: "{{ arg_app_dir }}/vpnclient"
unix_bin_dir: /usr/local/bin
unix_service_dir: /etc/systemd/system
