- name: Get VPNC state
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - vars/global_vars.yml

  tasks:
    - import_tasks: tasks/min_facts.yml

    - import_role:
        name: vpnc-state
