- name: Uninstall VPNC
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - vars/global_vars.yml

  tasks:
    - import_tasks: tasks/min_facts.yml

    - name: Uninstall VPNC
      import_role:
        name: vpnc-undeploy
