- name: Rollout new VPNC version
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - vars/global_vars.yml

  tasks:
    - import_tasks: tasks/min_facts.yml

    - name: Prepare artifact
      import_role:
        name: get-artifact

    - name: Prepare credentials
      import_role:
        name: get-credential

    - name: Verify VPNC state
      import_role:
        name: vpnc-state

    - name: Install VPNC
      when: not vpnc_state.is_exec or vpnc_state.is_broken
      import_role:
        name: vpnc-install
      vars:
        arg_vpn_install_force: True

    - name: Upgrade VPNC
      when: vpnc_state.is_exec and not vpnc_state.is_broken
      import_role:
        name: vpnc-upgrade

    - name: Check VPNC state
      import_role:
        name: vpnc-state
