- name: Get VPNC state
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - vars/global_vars.yml

  tasks:
    - name: Populate remote machine
      include_tasks: tasks/min_facts.yml

    - name: Verify VPNC state
      include_role:
        name: vpnc-state
      vars:
        arg_show_output: True
