- name: Extend VPNC subscription
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - vars/global_vars.yml

  tasks:
    - name: Populate remote machine
      include_tasks: tasks/min_facts.yml

    - name: Check VPNC state
      include_role:
        name: vpnc-state

    - name: Install VPNC if not yet installed
      when: not vpnc_state.is_exec or vpnc_state.is_broken
      assert:
        that: not vpnc_state.is_exec or vpnc_state.is_broken
        fail_msg: "VPNC is not yet installed on {{ inventory_hostname }}"

    - name: Add VPN account
      include_role:
        name: vpnc-extend
