- name: Rollout new VPNC version
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - vars/global_vars.yml

  tasks:
    - name: Populate remote machine
      include_tasks: tasks/min_facts.yml

    - name: Prepare artifact
      include_role:
        name: prepare-artifact

    - name: Check VPNC state
      include_role:
        name: vpnc-state

    - name: Evaluate Rollout Precondition
      ansible.builtin.set_fact:
        precondition_is_installed: "{{ not vpnc_state.is_exec or vpnc_state.is_broken or not (vpnc_state.status.app_state | default(False)) }}"
        precondition_is_upgraded: "{{ vpnc_state.status.app_state | default(False) }}"

    - name: Install VPNC if not yet installed
      when: precondition_is_installed
      include_role:
        name: vpnc-install
      vars:
        arg_vpn_install_force: True

      #TODO: Need check semver
    - name: Upgrade VPNC if already installed
      when: precondition_is_upgraded
      include_role:
        name: vpnc-upgrade

    - name: Verify VPNC state
      when: precondition_is_installed or precondition_is_upgraded
      include_role:
        name: vpnc-state
      vars:
        arg_show_output: True
        arg_assert_install: True
        arg_assert_work: {{ precondition_is_upgraded }}
