- name: Extend VPNC subscription
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - vars/global_vars.yml

  tasks:
    - name: Prepare credentials
      include_role:
        name: prepare-credential
      vars:
        arg_key_cert: "{{ inventory_hostname }}"

    - name: Populate remote machine
      include_tasks: tasks/min_facts.yml

    - name: Check VPNC state
      include_role:
        name: vpnc-state

    - name: Guard VPNC must be installed
      ansible.builtin.assert:
        that: vpnc_state.is_exec and not vpnc_state.is_broken
        msg: "VPNC is not yet installed on {{ inventory_hostname }}"

    - name: Add VPN account
      include_role:
        name: vpnc-extend
      vars:
        arg_vpn_conn: "{{ prepare_credential }}"

    - name: Verify VPNC state
      include_role:
        name: vpnc-state
