- name: Rollout new VPNC version
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - vars/global_vars.yml

  tasks:
    - name: Populate remote machine
      include_tasks: tasks/min_facts.yml

    - name: Prepare artifact
      include_role:
        name: prepare-artifact

    - name: Check VPNC state
      include_role:
        name: vpnc-state

    - name: Install VPNC if not yet installed
      when: not vpnc_state.is_exec or vpnc_state.is_broken
      include_role:
        name: vpnc-install
      vars:
        arg_vpn_install_force: True

      #TODO: Need check semver
    - name: Upgrade VPNC if already installed
      when: vpnc_state.is_exec and not vpnc_state.is_broken
      include_role:
        name: vpnc-upgrade

    - name: Verify VPNC state
      include_role:
        name: vpnc-state
